from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *


class ElementPropertiesView(QGroupBox):
    def __init__(self, matPropModel):
        super(ElementPropertiesView, self).__init__()
        self.viewModel = matPropModel
        self.layout = QGridLayout()
        self.layout.setHorizontalSpacing(40)
        self.layout.setVerticalSpacing(10)
        self.layout.setAlignment(Qt.AlignLeft | Qt.AlignTop)
        self.setInputs()
        self.setLayout(self.layout)

    def setInputs(self):
        materialGroupLabel = QLabel("Material Group " + str(self.viewModel.materialGroupId))
        materialGroupLabel.setFont(QFont('Helvetica', 16))
        self.layout.addWidget(materialGroupLabel, 0, 1, 1, 2)

        self.layout.setRowMinimumHeight(1, 30)

        saturatedConductivityLabel = QLabel("Saturated Conductivity")
        saturatedConductivityLabel.setFont(QFont('Helvetica', 14))
        self.layout.addWidget(saturatedConductivityLabel, 2, 1, 1, 2)

        hSaturatedConductivityLabel = QLabel("Horizontal")
        hSaturatedConductivityLabel.setFont(QFont('Helvetica', 12))
        self.layout.addWidget(hSaturatedConductivityLabel, 3, 1, 1, 2)
        self.FMOBX = QDoubleSpinBox(buttonSymbols = QDoubleSpinBox.NoButtons)
        self.FMOBX.setAlignment(Qt.AlignRight)
        self.FMOBX.setRange(-9999.99999, 9999.99999)
        self.FMOBX.setDecimals(5)
        self.FMOBX.setSingleStep(0.00001)
        self.FMOBX.setFixedWidth(100)
        self.FMOBX.valueChanged.connect(lambda value: self.viewModel.setValue("FMOBX", value))
        self.layout.addWidget(self.FMOBX, 4, 1)

        vSaturatedConductivityLabel = QLabel("Vertical")
        vSaturatedConductivityLabel.setFont(QFont('Helvetica', 12))
        self.layout.addWidget(vSaturatedConductivityLabel, 3, 2)
        self.FMOBY = QDoubleSpinBox(buttonSymbols = QDoubleSpinBox.NoButtons)
        self.FMOBY.setAlignment(Qt.AlignRight)
        self.FMOBY.setRange(-9999.99999, 9999.99999)
        self.FMOBY.setDecimals(5)
        self.FMOBY.setSingleStep(0.00001)
        self.FMOBY.setFixedWidth(100)
        self.FMOBY.valueChanged.connect(lambda value: self.viewModel.setValue("FMOBY", value))
        self.layout.addWidget(self.FMOBY, 4, 2)

        self.layout.setRowMinimumHeight(5, 20)

        dispersivityLabel = QLabel("Dispersivity")
        dispersivityLabel.setFont(QFont('Helvetica', 14))
        self.layout.addWidget(dispersivityLabel, 6, 1, 1, 2)

        transverseDispersLabel = QLabel("Transverse")
        transverseDispersLabel.setFont(QFont('Helvetica', 12))
        self.layout.addWidget(transverseDispersLabel, 7, 1)
        self.ETRANS = QDoubleSpinBox(buttonSymbols = QDoubleSpinBox.NoButtons)
        self.ETRANS.setAlignment(Qt.AlignRight)
        self.ETRANS.setRange(-9999.99999, 9999.99999)
        self.ETRANS.setDecimals(5)
        self.ETRANS.setSingleStep(0.00001)
        self.ETRANS.setFixedWidth(100)
        self.ETRANS.valueChanged.connect(lambda value: self.viewModel.setValue("ETRANS", value))
        self.layout.addWidget(self.ETRANS, 8, 1)

        longitudDispersLabel = QLabel("Longitudinal")
        longitudDispersLabel.setFont(QFont('Helvetica', 12))
        self.layout.addWidget(longitudDispersLabel, 7, 2)
        self.ELONG = QDoubleSpinBox(buttonSymbols = QDoubleSpinBox.NoButtons)
        self.ELONG.setAlignment(Qt.AlignRight)
        self.ELONG.setRange(-9999.99999, 9999.99999)
        self.ELONG.setDecimals(5)
        self.ELONG.setSingleStep(0.00001)
        self.ELONG.setFixedWidth(100)
        self.ELONG.valueChanged.connect(lambda value: self.viewModel.setValue("ELONG", value))
        self.layout.addWidget(self.ELONG, 8, 2)

        self.layout.setRowMinimumHeight(9, 40)

        porosityLabel = QLabel("Porosity")
        porosityLabel.setFont(QFont('Helvetica', 12))
        self.layout.addWidget(porosityLabel, 11, 1)
        self.POR = QDoubleSpinBox(buttonSymbols = QDoubleSpinBox.NoButtons)
        self.POR.setAlignment(Qt.AlignRight)
        self.POR.setRange(-9999.99999, 9999.99999)
        self.POR.setDecimals(5)
        self.POR.setSingleStep(0.00001)
        self.POR.setFixedWidth(100)
        self.POR.valueChanged.connect(lambda value: self.viewModel.setValue("POR", value))
        self.layout.addWidget(self.POR, 12, 1)

        moistureContentLabel = QLabel("Moisture Content")
        moistureContentLabel.setFont(QFont('Helvetica', 12))
        self.layout.addWidget(moistureContentLabel, 11, 2)
        self.TTA = QDoubleSpinBox(buttonSymbols = QDoubleSpinBox.NoButtons)
        self.TTA.setAlignment(Qt.AlignRight)
        self.TTA.setRange(-9999.99999, 9999.99999)
        self.TTA.setDecimals(5)
        self.TTA.setSingleStep(0.00001)
        self.TTA.setFixedWidth(100)
        self.TTA.valueChanged.connect(lambda value: self.viewModel.setValue("TTA", value))
        self.layout.addWidget(self.TTA, 12, 2)

        compressibilityLabel = QLabel("Compressibility")
        compressibilityLabel.setFont(QFont('Helvetica', 12))
        self.layout.addWidget(compressibilityLabel, 11, 3)
        self.ALPHA = QDoubleSpinBox(buttonSymbols = QDoubleSpinBox.NoButtons)
        self.ALPHA.setAlignment(Qt.AlignRight)
        self.ALPHA.setRange(-9999.99999, 9999.99999)
        self.ALPHA.setDecimals(5)
        self.ALPHA.setSingleStep(0.00001)
        self.ALPHA.setFixedWidth(100)
        self.ALPHA.valueChanged.connect(lambda value: self.viewModel.setValue("ALPHA", value))
        self.layout.addWidget(self.ALPHA, 12, 3)

        distributionLabel = QLabel("Distribution")
        distributionLabel.setFont(QFont('Helvetica', 12))
        self.layout.addWidget(distributionLabel, 13, 1)
        self.KD = QDoubleSpinBox(buttonSymbols = QDoubleSpinBox.NoButtons)
        self.KD.setAlignment(Qt.AlignRight)
        self.KD.setRange(-9999.99999, 9999.99999)
        self.KD.setDecimals(5)
        self.KD.setSingleStep(0.00001)
        self.KD.setFixedWidth(100)
        self.KD.valueChanged.connect(lambda value: self.viewModel.setValue("KD", value))
        self.layout.addWidget(self.KD, 14, 1)

        radDecayLabel = QLabel("Radioactive Decay")
        radDecayLabel.setFont(QFont('Helvetica', 12))
        self.layout.addWidget(radDecayLabel, 13, 2)
        self.LAMBDA = QDoubleSpinBox(buttonSymbols = QDoubleSpinBox.NoButtons)
        self.LAMBDA.setAlignment(Qt.AlignRight)
        self.LAMBDA.setRange(-9999.99999, 9999.99999)
        self.LAMBDA.setDecimals(5)
        self.LAMBDA.setSingleStep(0.00001)
        self.LAMBDA.setFixedWidth(100)
        self.LAMBDA.valueChanged.connect(lambda value: self.viewModel.setValue("LAMBDA", value))
        self.layout.addWidget(self.LAMBDA, 14, 2)

        dryBulkDensityLabel = QLabel("Dry Bulk Density")
        dryBulkDensityLabel.setFont(QFont('Helvetica', 12))
        self.layout.addWidget(dryBulkDensityLabel, 13, 3)
        self.RHO = QDoubleSpinBox(buttonSymbols = QDoubleSpinBox.NoButtons)
        self.RHO.setAlignment(Qt.AlignRight)
        self.RHO.setRange(-9999.99999, 9999.99999)
        self.RHO.setDecimals(5)
        self.RHO.setSingleStep(0.00001)
        self.RHO.setFixedWidth(100)
        self.RHO.valueChanged.connect(lambda value: self.viewModel.setValue("RHO", value))
        self.layout.addWidget(self.RHO, 14, 3)
